### PR TITLE
Soy Upgrade

### PR DESCRIPTION
**Pull request by solidjb**
Upgraded to the latest versions of the closure compiler and soy.  Minor modifications to a test based on changes from the new libraries.

### CODE REVIEW

**Comment by matiwinnetou** [comment]
Did you test this? Please keep in mind that latest soy libraries actually have a lot of changes that make some design decisions obsolete (one would really need to change rather a lot).

Just a plain upgrade however is always possible but today with latest soy I would write this library almost completely differently.

**Comment by solidjb** [comment]
I did test it. We needed to make significant changes to our templates but they rendered correctly. It seemed like s good small step to get the library up to the latest version. If you have larger changes to make that's cool too, but this was the minimum.

**Comment by solidjb** [comment]
Do you think you will release this change?  Will you bump versions to 2.0.0?

**Comment by solidjb** [comment]
Also, I don't know if you want to lay out some of your design thoughts in an email or github message, now that the libraries have been updated.  It is possible that my company would allow us to do some implementing of that stuff so that we can keep using the library (no promises)

**Comment by matiwinnetou** [comment]
Sure I can, yes I can release this soon.

**Comment by matiwinnetou** [comment]
Released: 2.0.0, should be available here soon:
https://repo1.maven.org/maven2/pl/matisoft/spring-soy-view/

**Pull request merged**
